version: "3.1"

services:
  mongo:
    container_name: u-palm-mongoDB
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: 125478963m
      MONGO_INITDB_DATABASE: UPalm
      MONGODB_DATABASE: UPalm
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db

  redis:
    container_name: u-palm-redis
    image: redis:7.2.4
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    links:
      - redis

volumes:
  mongodb:
  redis_volume_data:
